# Default values for zookeeper.
# This is a YAML-formatted file.
# Declare name/value pairs to be passed into your templates.
# name: value
Servers: 3
Cpu: "1"
Memory: "4Gi"
Heap: "2G"
Storage: "50Gi"
#StorageClass : default
ServerPort: 2888
LeaderElectionPort: 3888
ClientPort: 2181
Image: "gcr.io/google_samples/kubernetes-zookeeper:1.0-3.4.10"
ImagePullPolicy: "Always"
TickTimeMs: 2000
InitTicks: 10
SyncTicks: 5
ClientCnxns: 60
SnapRetain: 3
PurgeHours: 1
ProbeInitialDelaySeconds : 15
ProbeTimeoutSeconds : 5
AntiAffinity: "hard"
LogLevel: "INFO"
MaxSessionTimeout: 40000
MinSessionTimeout: 4000